/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas.besar.view;

import java.awt.Color;

/**
 *
 * @author LENOVO
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        iconPPTK = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        btnMaximize = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        iconUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        iconPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        menuKiri = new javax.swing.JPanel();
        menuPesan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menuForm = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        menuLogout = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        judulMenu = new javax.swing.JLabel();
        menuPengajuan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menuKanan = new javax.swing.JPanel();
        btnMinimize1 = new javax.swing.JLabel();
        btnMaximize1 = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JLabel();
        itemPesan = new javax.swing.JPanel();
        pTulis = new javax.swing.JPanel();
        iconTulis = new javax.swing.JLabel();
        pKotakMasuk = new javax.swing.JPanel();
        iconKotakMasuk = new javax.swing.JLabel();
        itemPengajuan = new javax.swing.JPanel();
        jCari = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        iconKirim = new javax.swing.JLabel();
        jKirim = new javax.swing.JLabel();
        itemForm = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        iconUnduh = new javax.swing.JLabel();
        iconPrint = new javax.swing.JLabel();
        jPrint = new javax.swing.JLabel();
        jUnduh = new javax.swing.JLabel();
        menuAwal = new javax.swing.JPanel();
        jMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi PPTK Gambung");
        setUndecorated(true);
        setResizable(false);

        panelLogin.setBackground(new java.awt.Color(102, 102, 102));
        panelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLoginMouseEntered(evt);
            }
        });

        iconPPTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/LOGO-GAMBUNG.png"))); // NOI18N

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("X");

        btnMinimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/MINIMIZE.png"))); // NOI18N

        btnMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/MAXIMIZE.png"))); // NOI18N

        inputPanel.setBackground(new java.awt.Color(204, 204, 204,50));

        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/PROFILE.png"))); // NOI18N

        txtUser.setBackground(new java.awt.Color(204, 204, 204));
        txtUser.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setText("Username");
        txtUser.setBorder(null);
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });

        iconPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/PASSWORD.png"))); // NOI18N

        txtPass.setBackground(new java.awt.Color(204, 204, 204));
        txtPass.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setText("Password");
        txtPass.setBorder(null);
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconUser)
                    .addComponent(iconPass))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(txtPass))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(iconPass))
                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("LOGIN");

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMaximize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                                .addComponent(iconPPTK)
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMaximize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1))
                    .addComponent(btnMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(iconPPTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        mainMenu.setBackground(new java.awt.Color(157, 158, 158));
        mainMenu.setPreferredSize(new java.awt.Dimension(600, 400));
        mainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuKiri.setBackground(new java.awt.Color(59, 59, 59));
        menuKiri.setPreferredSize(new java.awt.Dimension(140, 400));

        menuPesan.setBackground(new java.awt.Color(59, 59, 59));
        menuPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPesanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPesanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPesanMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/PESAN.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PESAN");

        javax.swing.GroupLayout menuPesanLayout = new javax.swing.GroupLayout(menuPesan);
        menuPesan.setLayout(menuPesanLayout);
        menuPesanLayout.setHorizontalGroup(
            menuPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPesanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(57, 57, 57))
        );
        menuPesanLayout.setVerticalGroup(
            menuPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPesanLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuForm.setBackground(new java.awt.Color(59, 59, 59));
        menuForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFormMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuFormMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuFormMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/FORM-BTN.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FORM BPB");

        javax.swing.GroupLayout menuFormLayout = new javax.swing.GroupLayout(menuForm);
        menuForm.setLayout(menuFormLayout);
        menuFormLayout.setHorizontalGroup(
            menuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFormLayout.createSequentialGroup()
                .addGroup(menuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuFormLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel5))
                    .addGroup(menuFormLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuFormLayout.setVerticalGroup(
            menuFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuFormLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        menuLogout.setBackground(new java.awt.Color(59, 59, 59));
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLogoutMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/LOGOUT.png"))); // NOI18N
        jLabel6.setText("LOGOUT");

        javax.swing.GroupLayout menuLogoutLayout = new javax.swing.GroupLayout(menuLogout);
        menuLogout.setLayout(menuLogoutLayout);
        menuLogoutLayout.setHorizontalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLogoutLayout.setVerticalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        judulMenu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        judulMenu.setForeground(new java.awt.Color(255, 255, 255));
        judulMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/PROFILE-MENU.png"))); // NOI18N
        judulMenu.setText("GUDANG");

        menuPengajuan.setBackground(new java.awt.Color(59, 59, 59));
        menuPengajuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPengajuanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPengajuanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPengajuanMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PENGAJUAN");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/PENGAJUAN.png"))); // NOI18N

        javax.swing.GroupLayout menuPengajuanLayout = new javax.swing.GroupLayout(menuPengajuan);
        menuPengajuan.setLayout(menuPengajuanLayout);
        menuPengajuanLayout.setHorizontalGroup(
            menuPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPengajuanLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(menuPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(menuPengajuanLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPengajuanLayout.setVerticalGroup(
            menuPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPengajuanLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout menuKiriLayout = new javax.swing.GroupLayout(menuKiri);
        menuKiri.setLayout(menuKiriLayout);
        menuKiriLayout.setHorizontalGroup(
            menuKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuPengajuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuKiriLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(judulMenu)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        menuKiriLayout.setVerticalGroup(
            menuKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuKiriLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(judulMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuPengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainMenu.add(menuKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 143, 410));

        menuKanan.setBackground(new java.awt.Color(157, 158, 158));
        menuKanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimize1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMinimize1.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/MINIMIZE.png"))); // NOI18N
        menuKanan.add(btnMinimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 11, -1, 30));

        btnMaximize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/MAXIMIZE.png"))); // NOI18N
        menuKanan.add(btnMaximize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 11, -1, 29));

        btnExit1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(255, 255, 255));
        btnExit1.setText("X");
        menuKanan.add(btnExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 11, -1, -1));

        itemPesan.setBackground(new java.awt.Color(157, 158, 158));

        pTulis.setBackground(new java.awt.Color(59, 59, 59));
        pTulis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pTulisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pTulisMouseExited(evt);
            }
        });

        iconTulis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        iconTulis.setForeground(new java.awt.Color(255, 255, 255));
        iconTulis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/TULIS PESAN.png"))); // NOI18N
        iconTulis.setText("TULIS PESAN");

        javax.swing.GroupLayout pTulisLayout = new javax.swing.GroupLayout(pTulis);
        pTulis.setLayout(pTulisLayout);
        pTulisLayout.setHorizontalGroup(
            pTulisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTulisLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(iconTulis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTulisLayout.setVerticalGroup(
            pTulisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTulisLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconTulis)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pKotakMasuk.setBackground(new java.awt.Color(59, 59, 59));
        pKotakMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pKotakMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pKotakMasukMouseExited(evt);
            }
        });

        iconKotakMasuk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        iconKotakMasuk.setForeground(new java.awt.Color(255, 255, 255));
        iconKotakMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/KOTAK MASUK-BTN.png"))); // NOI18N
        iconKotakMasuk.setText("KOTAK MASUK");

        javax.swing.GroupLayout pKotakMasukLayout = new javax.swing.GroupLayout(pKotakMasuk);
        pKotakMasuk.setLayout(pKotakMasukLayout);
        pKotakMasukLayout.setHorizontalGroup(
            pKotakMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKotakMasukLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(iconKotakMasuk)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pKotakMasukLayout.setVerticalGroup(
            pKotakMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKotakMasukLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(iconKotakMasuk)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout itemPesanLayout = new javax.swing.GroupLayout(itemPesan);
        itemPesan.setLayout(itemPesanLayout);
        itemPesanLayout.setHorizontalGroup(
            itemPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPesanLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(itemPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pKotakMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pTulis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        itemPesanLayout.setVerticalGroup(
            itemPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPesanLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(pTulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(pKotakMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        menuKanan.add(itemPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 350));

        itemPengajuan.setBackground(new java.awt.Color(157, 158, 158));

        jCari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCari.setForeground(new java.awt.Color(255, 255, 255));
        jCari.setText("Cari");

        txtCari.setBackground(new java.awt.Color(157, 158, 158));
        txtCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCari.setForeground(new java.awt.Color(255, 255, 255));
        txtCari.setBorder(null);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        iconKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/KIRIM-BTN.png"))); // NOI18N
        iconKirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconKirimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconKirimMouseExited(evt);
            }
        });

        jKirim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jKirim.setForeground(new java.awt.Color(255, 255, 255));
        jKirim.setText("Kirim");

        javax.swing.GroupLayout itemPengajuanLayout = new javax.swing.GroupLayout(itemPengajuan);
        itemPengajuan.setLayout(itemPengajuanLayout);
        itemPengajuanLayout.setHorizontalGroup(
            itemPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPengajuanLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jCari)
                .addGap(18, 18, 18)
                .addGroup(itemPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3)
                    .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemPengajuanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(itemPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jKirim, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconKirim, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        itemPengajuanLayout.setVerticalGroup(
            itemPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPengajuanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(itemPengajuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(iconKirim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jKirim)
                .addContainerGap())
        );

        menuKanan.add(itemPengajuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 350));

        itemForm.setBackground(new java.awt.Color(157, 158, 158));
        itemForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(117, 117, 117));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PDF");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel11)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel11)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        itemForm.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 390, -1));

        iconUnduh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/UNDUH.png"))); // NOI18N
        iconUnduh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconUnduhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconUnduhMouseExited(evt);
            }
        });
        itemForm.add(iconUnduh, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        iconPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/besar/icon/PRINT.png"))); // NOI18N
        iconPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconPrintMouseExited(evt);
            }
        });
        itemForm.add(iconPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPrint.setForeground(new java.awt.Color(255, 255, 255));
        jPrint.setText("PRINT");
        itemForm.add(jPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 290, 40, -1));

        jUnduh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jUnduh.setForeground(new java.awt.Color(255, 255, 255));
        jUnduh.setText("UNDUH");
        itemForm.add(jUnduh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        menuKanan.add(itemForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 350));

        menuAwal.setBackground(new java.awt.Color(157, 158, 158));

        jMenu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setText("Silahkan pilih menu");

        javax.swing.GroupLayout menuAwalLayout = new javax.swing.GroupLayout(menuAwal);
        menuAwal.setLayout(menuAwalLayout);
        menuAwalLayout.setHorizontalGroup(
            menuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(menuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuAwalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jMenu)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        menuAwalLayout.setVerticalGroup(
            menuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(menuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuAwalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuKanan.add(menuAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 350));

        mainMenu.add(menuKanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 0, 456, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     Color Abu = new Color(128,128,128);
     Color Abu2 = new Color(153,153,153);
     Color AbuTua = new Color(59,59,59);
     Color Putih = new Color(255,255,255);
     
    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        // TODO add your handling code here:
        txtUser.setText("");
    }//GEN-LAST:event_txtUserMouseClicked

    private void txtPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseClicked
        // TODO add your handling code here:
        txtPass.setText("");
    }//GEN-LAST:event_txtPassMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(Abu2);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(Putih);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        String Username;
        Username = txtUser.getText();
        
        if((Username.equals("Username"))||(Username.equals(""))){
            
        } else {
        txtUser.setText("Username");
        txtPass.setText("Password");
        panelLogin.setVisible(false);
        mainMenu.setVisible(true);
        
        menuAwal.setVisible(true);
        itemPesan.setVisible(false);
        itemPengajuan.setVisible(false);
        itemForm.setVisible(false);
        
        
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void menuPesanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPesanMouseEntered
        // TODO add your handling code here:
        menuPesan.setBackground(Abu);
        
    }//GEN-LAST:event_menuPesanMouseEntered

    private void menuPengajuanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPengajuanMouseEntered
        // TODO add your handling code here:
        menuPengajuan.setBackground(Abu);
    }//GEN-LAST:event_menuPengajuanMouseEntered

    private void menuFormMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFormMouseEntered
        // TODO add your handling code here:
        menuForm.setBackground(Abu);
    }//GEN-LAST:event_menuFormMouseEntered

    private void menuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseEntered
        // TODO add your handling code here:
        menuLogout.setBackground(Abu);
    }//GEN-LAST:event_menuLogoutMouseEntered

    private void menuPesanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPesanMouseExited
        // TODO add your handling code here:
        menuPesan.setBackground(AbuTua);
    }//GEN-LAST:event_menuPesanMouseExited

    private void menuPengajuanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPengajuanMouseExited
        // TODO add your handling code here:
        menuPengajuan.setBackground(AbuTua);
    }//GEN-LAST:event_menuPengajuanMouseExited

    private void menuFormMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFormMouseExited
        // TODO add your handling code here:
        menuForm.setBackground(AbuTua);
    }//GEN-LAST:event_menuFormMouseExited

    private void menuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseExited
        // TODO add your handling code here:
        menuLogout.setBackground(AbuTua);
    }//GEN-LAST:event_menuLogoutMouseExited

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        // TODO add your handling code here:
        panelLogin.setVisible(true);
        mainMenu.setVisible(false);
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void panelLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLoginMouseEntered
        // TODO add your handling code here:
        panelLogin.setVisible(true);
        mainMenu.setVisible(false);
    }//GEN-LAST:event_panelLoginMouseEntered

    private void menuPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPesanMouseClicked
        // TODO add your handling code here:
        menuAwal.setVisible(false);
        itemPesan.setVisible(true);
        itemPengajuan.setVisible(false);
        itemForm.setVisible(false);
        
    }//GEN-LAST:event_menuPesanMouseClicked

    private void menuPengajuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPengajuanMouseClicked
        // TODO add your handling code here:
        menuAwal.setVisible(false);
        itemPesan.setVisible(false);
        itemPengajuan.setVisible(true);
        itemForm.setVisible(false);
    }//GEN-LAST:event_menuPengajuanMouseClicked

    private void menuFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFormMouseClicked
        // TODO add your handling code here:
        menuAwal.setVisible(false);
        itemPesan.setVisible(false);
        itemPengajuan.setVisible(false);
        itemForm.setVisible(true);
    }//GEN-LAST:event_menuFormMouseClicked

    private void pTulisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTulisMouseEntered
        // TODO add your handling code here:
        pTulis.setBackground(Abu);
    }//GEN-LAST:event_pTulisMouseEntered

    private void pKotakMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pKotakMasukMouseEntered
        // TODO add your handling code here:
        pKotakMasuk.setBackground(Abu);
    }//GEN-LAST:event_pKotakMasukMouseEntered

    private void pTulisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTulisMouseExited
        // TODO add your handling code here:
        pTulis.setBackground(AbuTua);
    }//GEN-LAST:event_pTulisMouseExited

    private void pKotakMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pKotakMasukMouseExited
        // TODO add your handling code here:
        pKotakMasuk.setBackground(AbuTua);
    }//GEN-LAST:event_pKotakMasukMouseExited

    private void iconKirimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconKirimMouseEntered
        // TODO add your handling code here:
        jKirim.setForeground(AbuTua);
    }//GEN-LAST:event_iconKirimMouseEntered

    private void iconKirimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconKirimMouseExited
        // TODO add your handling code here:
        jKirim.setForeground(Color.WHITE);
    }//GEN-LAST:event_iconKirimMouseExited

    private void iconUnduhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconUnduhMouseEntered
        // TODO add your handling code here:
        jUnduh.setForeground(AbuTua);
    }//GEN-LAST:event_iconUnduhMouseEntered

    private void iconPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPrintMouseEntered
        // TODO add your handling code here:
        jPrint.setForeground(AbuTua);
    }//GEN-LAST:event_iconPrintMouseEntered

    private void iconUnduhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconUnduhMouseExited
        // TODO add your handling code here:
        jUnduh.setForeground(Color.WHITE);
    }//GEN-LAST:event_iconUnduhMouseExited

    private void iconPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPrintMouseExited
        // TODO add your handling code here:
        jPrint.setForeground(Color.WHITE);
    }//GEN-LAST:event_iconPrintMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnExit1;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JLabel btnMaximize;
    private javax.swing.JLabel btnMaximize1;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnMinimize1;
    private javax.swing.JLabel iconKirim;
    private javax.swing.JLabel iconKotakMasuk;
    private javax.swing.JLabel iconPPTK;
    private javax.swing.JLabel iconPass;
    private javax.swing.JLabel iconPrint;
    private javax.swing.JLabel iconTulis;
    private javax.swing.JLabel iconUnduh;
    private javax.swing.JLabel iconUser;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JPanel itemForm;
    private javax.swing.JPanel itemPengajuan;
    private javax.swing.JPanel itemPesan;
    private javax.swing.JLabel jCari;
    private javax.swing.JLabel jKirim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jMenu;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPrint;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jUnduh;
    private javax.swing.JLabel judulMenu;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel menuAwal;
    private javax.swing.JPanel menuForm;
    private javax.swing.JPanel menuKanan;
    private javax.swing.JPanel menuKiri;
    private javax.swing.JPanel menuLogout;
    private javax.swing.JPanel menuPengajuan;
    private javax.swing.JPanel menuPesan;
    private javax.swing.JPanel pKotakMasuk;
    private javax.swing.JPanel pTulis;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
